package net.blay09.mods.kleeslabs.fabric.datagen;

import net.blay09.mods.kleeslabs.tag.ModBlockTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.IntrinsicHolderTagsProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Block;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends IntrinsicHolderTagsProvider<Block> {
    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, Registries.BLOCK, registriesFuture, (block) -> block.builtInRegistryHolder().key());
    }

    @Override
    protected void addTags(HolderLookup.Provider arg) {
        tag(ModBlockTags.SLABS).addOptionalTag(BlockTags.SLABS);
        tag(ModBlockTags.VERTICAL_SLABS).addOptionalTag(ModBlockTags.QUARK_VERTICAL_SLABS).addOptionalTag(ModBlockTags.ENCHANTED_VERTICAL_SLABS);
        getOrCreateRawBuilder(ModBlockTags.QUARK_VERTICAL_SLABS)
                .addOptionalElement(quark("acacia_vertical_slab"))
                .addOptionalElement(quark("ancient_planks_vertical_slab"))
                .addOptionalElement(quark("andesite_bricks_vertical_slab"))
                .addOptionalElement(quark("andesite_vertical_slab"))
                .addOptionalElement(quark("azalea_planks_vertical_slab"))
                .addOptionalElement(quark("bamboo_mosaic_vertical_slab"))
                .addOptionalElement(quark("bamboo_vertical_slab"))
                .addOptionalElement(quark("birch_vertical_slab"))
                .addOptionalElement(quark("black_shingles_vertical_slab"))
                .addOptionalElement(quark("blackstone_bricks_vertical_slab"))
                .addOptionalElement(quark("blackstone_vertical_slab"))
                .addOptionalElement(quark("blossom_planks_vertical_slab"))
                .addOptionalElement(quark("blue_nether_bricks_vertical_slab"))
                .addOptionalElement(quark("blue_shingles_vertical_slab"))
                .addOptionalElement(quark("brick_vertical_slab"))
                .addOptionalElement(quark("brown_shingles_vertical_slab"))
                .addOptionalElement(quark("calcite_bricks_vertical_slab"))
                .addOptionalElement(quark("calcite_vertical_slab"))
                .addOptionalElement(quark("cherry_vertical_slab"))
                .addOptionalElement(quark("cobbled_deepslate_vertical_slab"))
                .addOptionalElement(quark("cobblestone_bricks_vertical_slab"))
                .addOptionalElement(quark("cobblestone_vertical_slab"))
                .addOptionalElement(quark("crimson_vertical_slab"))
                .addOptionalElement(quark("cut_copper_vertical_slab"))
                .addOptionalElement(quark("cut_red_sandstone_vertical_slab"))
                .addOptionalElement(quark("cut_sandstone_vertical_slab"))
                .addOptionalElement(quark("cut_soul_sandstone_vertical_slab"))
                .addOptionalElement(quark("cyan_shingles_vertical_slab"))
                .addOptionalElement(quark("dark_oak_vertical_slab"))
                .addOptionalElement(quark("dark_prismarine_vertical_slab"))
                .addOptionalElement(quark("deepslate_brick_vertical_slab"))
                .addOptionalElement(quark("deepslate_tile_vertical_slab"))
                .addOptionalElement(quark("diorite_bricks_vertical_slab"))
                .addOptionalElement(quark("diorite_vertical_slab"))
                .addOptionalElement(quark("dirt_bricks_vertical_slab"))
                .addOptionalElement(quark("dripstone_block_vertical_slab"))
                .addOptionalElement(quark("dripstone_bricks_vertical_slab"))
                .addOptionalElement(quark("duskbound_block_vertical_slab"))
                .addOptionalElement(quark("end_stone_brick_vertical_slab"))
                .addOptionalElement(quark("exposed_cut_copper_vertical_slab"))
                .addOptionalElement(quark("granite_bricks_vertical_slab"))
                .addOptionalElement(quark("granite_vertical_slab"))
                .addOptionalElement(quark("gray_shingles_vertical_slab"))
                .addOptionalElement(quark("green_shingles_vertical_slab"))
                .addOptionalElement(quark("iron_plate_vertical_slab"))
                .addOptionalElement(quark("jasper_bricks_vertical_slab"))
                .addOptionalElement(quark("jasper_vertical_slab"))
                .addOptionalElement(quark("jungle_vertical_slab"))
                .addOptionalElement(quark("light_blue_shingles_vertical_slab"))
                .addOptionalElement(quark("light_gray_shingles_vertical_slab"))
                .addOptionalElement(quark("lime_shingles_vertical_slab"))
                .addOptionalElement(quark("limestone_bricks_vertical_slab"))
                .addOptionalElement(quark("limestone_vertical_slab"))
                .addOptionalElement(quark("magenta_shingles_vertical_slab"))
                .addOptionalElement(quark("mangrove_vertical_slab"))
                .addOptionalElement(quark("midori_block_vertical_slab"))
                .addOptionalElement(quark("mossy_cobblestone_bricks_vertical_slab"))
                .addOptionalElement(quark("mossy_cobblestone_vertical_slab"))
                .addOptionalElement(quark("mossy_stone_brick_vertical_slab"))
                .addOptionalElement(quark("mud_brick_vertical_slab"))
                .addOptionalElement(quark("myalite_bricks_vertical_slab"))
                .addOptionalElement(quark("myalite_vertical_slab"))
                .addOptionalElement(quark("nether_brick_vertical_slab"))
                .addOptionalElement(quark("netherrack_bricks_vertical_slab"))
                .addOptionalElement(quark("oak_vertical_slab"))
                .addOptionalElement(quark("orange_shingles_vertical_slab"))
                .addOptionalElement(quark("oxidized_cut_copper_vertical_slab"))
                .addOptionalElement(quark("permafrost_bricks_vertical_slab"))
                .addOptionalElement(quark("permafrost_vertical_slab"))
                .addOptionalElement(quark("pink_shingles_vertical_slab"))
                .addOptionalElement(quark("polished_andesite_vertical_slab"))
                .addOptionalElement(quark("polished_blackstone_brick_vertical_slab"))
                .addOptionalElement(quark("polished_blackstone_vertical_slab"))
                .addOptionalElement(quark("polished_calcite_vertical_slab"))
                .addOptionalElement(quark("polished_deepslate_vertical_slab"))
                .addOptionalElement(quark("polished_diorite_vertical_slab"))
                .addOptionalElement(quark("polished_dripstone_vertical_slab"))
                .addOptionalElement(quark("polished_granite_vertical_slab"))
                .addOptionalElement(quark("polished_jasper_vertical_slab"))
                .addOptionalElement(quark("polished_limestone_vertical_slab"))
                .addOptionalElement(quark("polished_myalite_vertical_slab"))
                .addOptionalElement(quark("polished_shale_vertical_slab"))
                .addOptionalElement(quark("polished_tuff_vertical_slab"))
                .addOptionalElement(quark("prismarine_brick_vertical_slab"))
                .addOptionalElement(quark("prismarine_vertical_slab"))
                .addOptionalElement(quark("purple_shingles_vertical_slab"))
                .addOptionalElement(quark("purpur_vertical_slab"))
                .addOptionalElement(quark("quartz_vertical_slab"))
                .addOptionalElement(quark("raw_copper_bricks_vertical_slab"))
                .addOptionalElement(quark("raw_gold_bricks_vertical_slab"))
                .addOptionalElement(quark("raw_iron_bricks_vertical_slab"))
                .addOptionalElement(quark("red_nether_brick_vertical_slab"))
                .addOptionalElement(quark("red_sandstone_bricks_vertical_slab"))
                .addOptionalElement(quark("red_sandstone_vertical_slab"))
                .addOptionalElement(quark("red_shingles_vertical_slab"))
                .addOptionalElement(quark("rusty_iron_plate_vertical_slab"))
                .addOptionalElement(quark("sandstone_bricks_vertical_slab"))
                .addOptionalElement(quark("sandstone_vertical_slab"))
                .addOptionalElement(quark("shale_bricks_vertical_slab"))
                .addOptionalElement(quark("shale_vertical_slab"))
                .addOptionalElement(quark("shingles_vertical_slab"))
                .addOptionalElement(quark("smooth_quartz_vertical_slab"))
                .addOptionalElement(quark("smooth_red_sandstone_vertical_slab"))
                .addOptionalElement(quark("smooth_sandstone_vertical_slab"))
                .addOptionalElement(quark("smooth_soul_sandstone_vertical_slab"))
                .addOptionalElement(quark("smooth_stone_vertical_slab"))
                .addOptionalElement(quark("soul_sandstone_bricks_vertical_slab"))
                .addOptionalElement(quark("soul_sandstone_vertical_slab"))
                .addOptionalElement(quark("spruce_vertical_slab"))
                .addOptionalElement(quark("stone_brick_vertical_slab"))
                .addOptionalElement(quark("stone_vertical_slab"))
                .addOptionalElement(quark("thatch_vertical_slab"))
                .addOptionalElement(quark("tuff_bricks_vertical_slab"))
                .addOptionalElement(quark("tuff_vertical_slab"))
                .addOptionalElement(quark("warped_vertical_slab"))
                .addOptionalElement(quark("waxed_cut_copper_vertical_slab"))
                .addOptionalElement(quark("waxed_exposed_cut_copper_vertical_slab"))
                .addOptionalElement(quark("waxed_oxidized_cut_copper_vertical_slab"))
                .addOptionalElement(quark("waxed_weathered_cut_copper_vertical_slab"))
                .addOptionalElement(quark("weathered_cut_copper_vertical_slab"))
                .addOptionalElement(quark("white_shingles_vertical_slab"))
                .addOptionalElement(quark("yellow_shingles_vertical_slab"));
        getOrCreateRawBuilder(ModBlockTags.ENCHANTED_VERTICAL_SLABS)
                .addOptionalElement(enchantedVerticalSlabs("vertical_acacia_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_andesite_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_bamboo_mosaic_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_bamboo_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_birch_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_blackstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_cherry_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_cobbled_deepslate_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_cobblestone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_crimson_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_cut_copper_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_cut_red_sandstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_cut_sandstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_dark_oak_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_dark_prismarine_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_deepslate_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_deepslate_tile_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_diorite_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_end_stone_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_exposed_cut_copper_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_granite_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_jungle_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_mangrove_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_mossy_cobblestone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_mossy_stone_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_mud_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_nether_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_oak_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_oxidized_cut_copper_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_petrified_oak_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_polished_andesite_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_polished_blackstone_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_polished_blackstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_polished_deepslate_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_polished_diorite_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_polished_granite_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_prismarine_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_prismarine_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_purpur_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_quartz_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_red_nether_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_red_sandstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_sandstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_smooth_quartz_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_smooth_red_sandstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_smooth_sandstone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_smooth_stone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_spruce_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_stone_brick_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_stone_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_warped_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_waxed_cut_copper_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_waxed_exposed_cut_copper_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_waxed_oxidized_cut_copper_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_waxed_weathered_cut_copper_slab"))
                .addOptionalElement(enchantedVerticalSlabs("vertical_weathered_cut_copper_slab"));

    }

    private static ResourceLocation quark(String path) {
        return ResourceLocation.fromNamespaceAndPath("quark", path);
    }

    private static ResourceLocation enchantedVerticalSlabs(String path) {
        return ResourceLocation.fromNamespaceAndPath("enchanted-vertical-slabs", path);
    }

}
