modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="kleeslabs"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="kleeslabs.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "kleeslabs.mixins.json"
[[mixins]]
config = "kleeslabs.neoforge.mixins.json"
[[dependencies.kleeslabs]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.kleeslabs]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.kleeslabs]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
